s = set()
n = int(input("Enter Number:"))
s.add(n)
n = int(input("Enter Number:"))
s.add(n)
n = int(input("Enter Number:"))
s.add(n)
n = int(input("Enter Number:"))
s.add(n)
n = int(input("Enter Number:"))
s.add(n)
n = int(input("Enter Number:"))
s.add(n)
n = int(input("Enter Number:"))
s.add(n)
n = int(input("Enter Number:"))
s.add(n)
n = int(input("Enter Number:"))
s.add(n)
print(s)